name: Sync docs README

on:
  push:
    branches: [ main ]
    paths:
      - README.md

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Copy root README into docs
        run: |
          mkdir -p docs
          cp README.md docs/README.md
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: sync docs/README.md from root"
          file_pattern: docs/README.md
